# this is sample schema file for report objects

---
initial_entries: 5
randomize: false
displayName: _firstname_ _lastname_
id: _firstname_._lastname_
created: _createdtimestamp_
lastAccess: _itemtimestamp_
...